# fly.toml app configuration file generated for grammareon on 2023-05-19T17:17:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grammareon"
primary_region = "hkg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
